### ISSUE TITLE
[Feature]: freezedの導入

### ISSUE THREAD

**Issue by komugi8** [yuru-fuwa/maiporarisu#35]
### 機能の説明

modelクラスを作成するために有用なpackageであるfreezedを導入する

### Todo

- [x] freezedの導入
  - [x] freezed install
  - [x] freezed annotation install
  - [x] build runner install
- [x] task model の生成
- [x] get, postリクエストをtask modelに対応
